name: The Last Candle GC pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  front:
    name: Build docker images
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./Sources/Frontend/.
          file: ./Sources/Frontend/Dockerfile
          push: false
          tags: |
            the-last-candle-front:${{github.run_number}}
            the-last-candle-front:latest
      -
        name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./Sources/Backend/.
          file: ./Sources/Backend/Dockerfile
          push: false
          tags: |
            the-last-candle-back:${{github.run_number}}
            the-last-candle-back:latest
